name: .NET 7 Web API CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup .NET 7 SDK
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore Kemo.sln

    # Build the project
    - name: Build
      run: dotnet build Kemo.sln --configuration Release --no-restore

    # Run tests here if you have any
    # - name: Test
    #   run: dotnet test Kemo.sln --no-build --verbosity normal

    # Publish the Web API project
    - name: Publish Web API
      run: dotnet publish api/api.csproj --configuration Release --no-build --output Api/publish

    # Upload the published artifacts
    - name: Upload published Web API
      uses: actions/upload-artifact@v3
      with:
        name: published-web-api
        path: Api/publish

